### PR TITLE
Simple documentation 

### LINKED ISSUE #13: Static website for the documentation
Hello everyone! I just read about this project on the Udacity forums and I'm very excited to start contributing to it.

I have an idea to further push this project by presenting it in a lightweight static website. I have used HUGO framework before and it would make it easier to attract more help. What do you think? @remon

### PR DESCRIPTION
**Pull request by ammarasmro**
Hello everyone, I just finished implementing a simple documentation for this project. I used [mkdocs](https://www.mkdocs.org/) since it is built using Python and further development doesn't require knowledge of other languages.

A demo of this documentation is on my repo:
[Documentation](http://ammarasmaro.com/pythonCodes/)

The website content will reside in the docs folder and the markdown content will be in the documentation_utils folder.

I implemented a simple script to automate the task of rendering the documentation and it can be carried on by the maintainers every time someone uploads a script. 

To setup your system
1. First install mkdocs on your machine from [Download page](https://www.mkdocs.org/#installation)
2. Change the permission of the script to make it executable by running this command

```bash
chmod +x compile-pages.sh
```

3. Run the script with this command

```bash
./compile-pages.sh
```

4. Run `git add` and 'git commit` then `git push` to push the changes

The last script runs the python_to_markdown_compiler python code so no need to run that.

> This script relies on the fact that you have python3 installed and can be accessed through the command `python3`

@remon  @ammore5 please let me know what you think and if I need to fix anything

fixes #13

### CODE REVIEW

**Comment by dimaalmasri** [comment]
great effort , i like it
 :1st_place_medal:

**Comment by ammarasmro** [comment]
Thank you @dimaalmasri @Azharoo I really appreciate your feedback

**Comment by remon** [comment]
@ammarasmro  more than amazing , I really liked it

**Comment by ammarasmro** [comment]
Thanks @remon 
Is there any chance this will request will get merged? Should I fix something in it?

**Pull request merged**
